# Generated by Django 4.1.7 on 2023-03-28 16:55

import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='comission_validation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=130)),
                ('desription', models.TextField()),
                ('post_needed', models.CharField(max_length=250)),
                ('validation', models.CharField(choices=[('True', 'True'), ('False', 'False')], max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='ensignant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(max_length=200)),
                ('rating', models.IntegerField(validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(0)])),
            ],
        ),
        migrations.CreateModel(
            name='message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='themes_to_validate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to='')),
                ('specialite', models.CharField(choices=[('sepcialité1', 'sepcialité1'), ('sepcialité2', 'sepcialité2'), ('sepcialité3', 'sepcialité3')], max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='validated_themes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to='')),
                ('specialite', models.CharField(choices=[('sepcialité1', 'sepcialité1'), ('sepcialité2', 'sepcialité2'), ('sepcialité3', 'sepcialité3')], max_length=200)),
                ('status', models.CharField(choices=[('Accepted', 'Accepted'), ('Rejected', 'Rejected')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('speciality', models.CharField(max_length=300)),
                ('interested', models.CharField(max_length=400)),
                ('CV', models.FileField(blank=True, max_length=1999999, upload_to='CVs')),
                ('study_level', models.CharField(choices=[('L3', 'L3'), ('M2', 'M2'), ('doctorate', 'doctorate')], max_length=30)),
                ('github_link', models.URLField(max_length=300)),
                ('linkedin_link', models.URLField(max_length=300)),
                ('Role', models.CharField(choices=[('Binome', 'Binome'), ('monome', 'monome'), ('None', 'None')], default='None', max_length=20)),
                ('binome', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='binome', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='owner', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('pourcentage', models.IntegerField(validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(10)])),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='resp_epcialit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialite', models.CharField(blank=True, choices=[('sepcialité1', 'sepcialité1'), ('sepcialité2', 'sepcialité2'), ('sepcialité3', 'sepcialité3')], max_length=200, null=True)),
                ('ensignant_re', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='API.ensignant')),
            ],
        ),
        migrations.CreateModel(
            name='pub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.CharField(choices=[('etudiant', 'etudiant'), ('ensignant', 'ensignant'), ('entreprise', 'entreprise')], max_length=30)),
                ('main_text', models.CharField(max_length=300)),
                ('description_text', models.TextField()),
                ('type', models.CharField(choices=[('question', 'question'), ('theme', 'theme')], max_length=30)),
                ('keywords', models.CharField(max_length=400)),
                ('date', models.DateField(default=datetime.date.today)),
                ('comission', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='API.comission_validation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titel', models.CharField(max_length=200)),
                ('decription', models.TextField()),
                ('date', models.DateTimeField(default=datetime.date.today)),
                ('notification_type', models.CharField(choices=[('notification_binome', 'notification_binome'), ('notification_ensignant', 'notification_ensignant'), ('notification_responsable', 'notification_responsable')], max_length=100)),
                ('id_pub', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='API.pub')),
                ('send_from', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='send_from', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='jury',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jury_nd', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='m_jury2', to=settings.AUTH_USER_MODEL)),
                ('m_jury_st', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='m_jury1', to=settings.AUTH_USER_MODEL)),
                ('president', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='president', to=settings.AUTH_USER_MODEL)),
                ('themes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='themes', to='API.pub')),
            ],
        ),
        migrations.AddField(
            model_name='ensignant',
            name='themes_proposed',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.pub'),
        ),
        migrations.AddField(
            model_name='ensignant',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('date', models.DateField(default=datetime.date.today)),
                ('comment_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('pub', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.pub')),
            ],
        ),
        migrations.AddField(
            model_name='comission_validation',
            name='ensignant1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='m_comission1', to='API.ensignant'),
        ),
        migrations.AddField(
            model_name='comission_validation',
            name='ensignant2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='m_comission2', to='API.ensignant'),
        ),
        migrations.AddField(
            model_name='comission_validation',
            name='ensignant3',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='m_comission3', to='API.ensignant'),
        ),
        migrations.AddField(
            model_name='comission_validation',
            name='theme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.themes_to_validate'),
        ),
    ]
