# Generated by Django 4.1.5 on 2023-02-17 18:35

import API.models
import datetime
from django.db import migrations, models
import django.db.models.deletion
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='comment',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('comment_by', djongo.models.fields.EmbeddedField(model_container=API.models.user)),
                ('post', djongo.models.fields.EmbeddedField(model_container=API.models.pub)),
                ('text', models.TextField()),
                ('date', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='company_profile',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=130)),
                ('description', models.TextField()),
                ('post_needed', models.CharField(max_length=250)),
                ('validation', models.CharField(choices=[('true', 'true'), ('false', 'false')], max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='message',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('sender', djongo.models.fields.EmbeddedField(model_container=API.models.user)),
                ('date', models.DateField(default=datetime.date.today)),
                ('message_text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='profile',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('user', djongo.models.fields.EmbeddedField(model_container=API.models.user)),
                ('speciality', models.CharField(max_length=300)),
                ('interested', models.CharField(max_length=400)),
                ('university_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='pub',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('user', djongo.models.fields.EmbeddedField(model_container=API.models.user)),
                ('text', models.TextField()),
                ('pub_type', models.CharField(choices=[('question', 'question'), ('theme', 'theme')], max_length=30)),
                ('date', models.DateField(default=datetime.date.today)),
                ('type', models.CharField(choices=[('theme', 'theme'), ('question', 'question')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='skill',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('user', djongo.models.fields.EmbeddedField(model_container=API.models.user)),
                ('skill_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ensignant_profile',
            fields=[
                ('profile_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='API.profile')),
                ('grade', models.CharField(max_length=200)),
                ('rating', models.IntegerField()),
                ('departement', models.CharField(max_length=300)),
            ],
            bases=('API.profile',),
        ),
        migrations.CreateModel(
            name='student_profile',
            fields=[
                ('profile_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='API.profile')),
                ('binome', djongo.models.fields.EmbeddedField(model_container=API.models.user)),
                ('CV', models.FileField(blank=True, max_length=1999999, upload_to='CVs')),
                ('study_level', models.CharField(choices=[('L3', 'L3'), ('M2', 'M2'), ('doctorate', 'doctorate')], max_length=30)),
                ('github_link', models.URLField(max_length=300)),
                ('linkedin_link', models.URLField(max_length=300)),
            ],
            bases=('API.profile',),
        ),
    ]
