# Generated by Django 4.1.7 on 2023-02-20 22:30

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='company_profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=130)),
                ('desription', models.TextField()),
                ('post_needed', models.CharField(max_length=250)),
                ('validation', models.CharField(choices=[('true', 'true'), ('false', 'false')], max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('speciality', models.CharField(max_length=300)),
                ('interested', models.CharField(max_length=400)),
                ('university_name', models.CharField(max_length=200)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ensignant_profile',
            fields=[
                ('profile_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='API.profile')),
                ('grade', models.CharField(max_length=200)),
                ('rating', models.IntegerField()),
                ('departement', models.CharField(max_length=300)),
            ],
            bases=('API.profile',),
        ),
        migrations.CreateModel(
            name='skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_name', models.CharField(max_length=200)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='pub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('pub_type', models.CharField(choices=[('question', 'question'), ('theme', 'theme')], max_length=30)),
                ('date', models.DateField(default=datetime.date.today)),
                ('type', models.CharField(choices=[('theme', 'theme'), ('question', 'question')], max_length=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('date', models.DateField(default=datetime.date.today)),
                ('comment_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('pub', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.pub')),
            ],
        ),
        migrations.CreateModel(
            name='student_profile',
            fields=[
                ('profile_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='API.profile')),
                ('CV', models.FileField(blank=True, max_length=1999999, upload_to='CVs')),
                ('study_level', models.CharField(choices=[('L3', 'L3'), ('M2', 'M2'), ('doctorate', 'doctorate')], max_length=30)),
                ('github_link', models.URLField(max_length=300)),
                ('linkedin_link', models.URLField(max_length=300)),
                ('binome', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            bases=('API.profile',),
        ),
    ]
