# Generated by Django 4.1.7 on 2023-03-07 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0002_alter_ensignant_profile_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ensignant_profile',
            name='departement',
        ),
        migrations.AlterField(
            model_name='company_profile',
            name='validation',
            field=models.CharField(choices=[('True', 'True'), ('False', 'False')], max_length=30),
        ),
    ]
