# Generated by Django 4.1.5 on 2023-02-01 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0003_alter_pub_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_profile',
            name='CV',
            field=models.FileField(blank=True, max_length=1999999, upload_to='CVs'),
        ),
    ]
